[package]
name = "cheka-ui"
version = "0.2.0-dev"
edition = "2024"
description = "Panel y bandeja de cheka (Tauri)"

[build-dependencies]
tauri-build = "2"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
